version: "3.7"

services:
  sysAppService:
    image: golang:1.17.2-alpine
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - ./pem/pkg:/go/pkg
    command: >
      sh -c "cd /app && 
            sh scripts/generate.sh &&
            sh scripts/build.sh &&
            sh scripts/run.sh" 
    depends_on:
      - "postgreSQL"
      - "rabbitMQ"
  mailsMicroservice:
    image: golang:1.17.2-alpine
    volumes:
      - ./:/app
      - ./pem/pkg:/go/pkg
    command: >
      sh -c "cd /app && 
            sh scripts/buildMailsMicroservice.sh &&
            sh scripts/runMailsMicroservice.sh" 
    depends_on:
      - "postgreSQL"
      - "rabbitMQ"
  postgreSQL:
    image: postgres
    hostname: postgres 
    restart: always
    volumes:
      - ./pem/pgdata:/var/lib/postgresql/data
      - ./pem:/pem
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_USER=usuario
      - POSTGRES_DB=miBD
  rabbitMQ:
    image:  rabbitmq:3.9-management
    container_name: 'SYS_RABBIT_MQ'
    hostname: rabbit
    restart:  always
    volumes:
      - ./pem:/pem
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./pem/rabbit:/var/lib/rabbitmq
    depends_on:
      - "postgreSQL"



