version: "3.7"

services:

  alamano_service:
    image: golang:1.17.2-alpine
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    command: >
      sh -c "cd /app && sh scripts/build.sh && sh scripts/run.sh"
  
