// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegisterInput struct {
	User *UserInput `json:"user"`
}

type User struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	Identification string `json:"identification"`
	Image          string `json:"image"`
	Password       string `json:"password"`
	RoleID         int    `json:"role_id"`
}

type UserInput struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
	Identification string `json:"identification"`
	Image          string `json:"image"`
	Password       string `json:"password"`
	RoleID         int    `json:"role_id"`
}
